USE [master]
GO

/****** Object:  Database [Jenkins]    Script Date: 12/10/2013 5:09:43 PM ******/
CREATE DATABASE [Jenkins] ON  PRIMARY 
( NAME = N'Jenkins', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Jenkins.mdf' , SIZE = 78528KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Jenkins_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Jenkins_log.ldf' , SIZE = 219264KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Jenkins] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Jenkins].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Jenkins] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Jenkins] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Jenkins] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Jenkins] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Jenkins] SET ARITHABORT OFF 
GO

ALTER DATABASE [Jenkins] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Jenkins] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Jenkins] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Jenkins] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Jenkins] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Jenkins] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Jenkins] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Jenkins] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Jenkins] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Jenkins] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Jenkins] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Jenkins] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Jenkins] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Jenkins] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Jenkins] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Jenkins] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Jenkins] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Jenkins] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Jenkins] SET RECOVERY FULL 
GO

ALTER DATABASE [Jenkins] SET  MULTI_USER 
GO

ALTER DATABASE [Jenkins] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Jenkins] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Jenkins] SET  READ_WRITE 
GO


